#
# Makefile for MStar Semutex device drivers.
#

# general options
EXTRA_CFLAGS      +=  -Idrivers/mstar2/include
EXTRA_CFLAGS      +=  -Idrivers/mstar2/drv/tee_shm

# specific options
EXTRA_CFLAGS      +=

# files
obj-y	+= mdrv_teeshm.o
