# general options
EXTRA_CFLAGS      +=  -Idrivers/mstar2/include
EXTRA_CFLAGS      +=  -Idrivers/mstar2/drv/hdmitx4vx1
EXTRA_CFLAGS      +=  -Iinclude/linux

# specific options

# files
obj-$(CONFIG_MSTAR_HDMITX4VX1)             := mdrv-hdmitx4vx1.o

mdrv-hdmitx4vx1-objs    += mdrv_hdmitx4vx1.o mdrv_hdmitx4vx1_io.o
