#
# Makefile for MStar pnl cust functions
#

# general options
#EXTRA_CFLAGS      +=  -Idrivers/mstar2/include
#EXTRA_CFLAGS      +=  -Idrivers/mstar2/drv/armce_test
#EXTRA_CFLAGS      +=  -Idrivers/mstar2/include/sys/common

# files
obj-$(CONFIG_MP_ARMCE_TEST) += mdrv_armv8ce_test.o

#mdrv-armv8ce-test-objs      += mdrv_armv8ce_test.o
