obj-$(CONFIG_MFD_IAXXX)		+= iaxxx-odsp-driver.o
iaxxx-odsp-driver-objs			:= iaxxx-odsp-celldrv.o

# ifeq ($(CONFIG_MFD_IAXXX), m)
#
# obj-$(CONFIG_MFD_IAXXX)		+= iaxxx-odsp-driver.o
# iaxxx-odsp-driver-objs		:= iaxxx-odsp-celldrv.o
#
# else
#
# obj-$(CONFIG_MFD_IAXXX)		+= iaxxx-odsp-celldrv.o
#
# endif
