EXTRA_CFLAGS    +=  -Idrivers/mstar2/include/
EXTRA_CFLAGS    +=  -Idrivers/mstar2/drv/qos/
obj-y +=    mdrv_qos_drv.o
obj-y +=    cpu/cpuqos_drv.o
obj-y +=    cpu/cpuqos_load.o
obj-y +=    cpu/cpuqos_proc.o
obj-y +=    cpu/cpuqos_dts.o
