/*
 * iaxxx-register-defs-pad-ctrl.h
 *
 * Copyright (c) 2018 Knowles, inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/**********************************************************
 * This file is generated by running a format script
 * on header files shared by Firmware.
 *
 * DO NOT EDIT.
 *
 *********************************************************/

#ifndef __IAXXX_REGISTER_DEFS_PAD_CTRL_H__
#define __IAXXX_REGISTER_DEFS_PAD_CTRL_H__

/*** The base address for this set of registers ***/
#define IAXXX_PAD_CTRL_REGS_ADDR (0x40003000)

/*** PAD_CTRL_CLK_IN (0x40003000) ***/
/*
 * This register is used for pad CLK_IN's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_CLK_IN_ADDR (0x40003000)
#define IAXXX_PAD_CTRL_CLK_IN_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_CLK_IN_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_CLK_IN_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_CLK_IN_RESET_VAL 0x00000028

/*
 * This field is used to control Driver Disabled State Control for pad
 * CLK_IN, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_CLK_IN_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_CLK_IN_DDST_RESET_VAL 0x0
#define IAXXX_PAD_CTRL_CLK_IN_DDST_POS 0
#define IAXXX_PAD_CTRL_CLK_IN_DDST_SIZE 2
#define IAXXX_PAD_CTRL_CLK_IN_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad CLK_IN.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_CLK_IN_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_CLK_IN_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_CLK_IN_REN_POS 3
#define IAXXX_PAD_CTRL_CLK_IN_REN_SIZE 1
#define IAXXX_PAD_CTRL_CLK_IN_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad CLK_IN.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_CLK_IN_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_CLK_IN_SMT_RESET_VAL 0x0
#define IAXXX_PAD_CTRL_CLK_IN_SMT_POS 4
#define IAXXX_PAD_CTRL_CLK_IN_SMT_SIZE 1
#define IAXXX_PAD_CTRL_CLK_IN_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad CLK_IN.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_CLK_IN_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_CLK_IN_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_CLK_IN_SR_POS 5
#define IAXXX_PAD_CTRL_CLK_IN_SR_SIZE 1
#define IAXXX_PAD_CTRL_CLK_IN_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad CLK_IN.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_CLK_IN_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_CLK_IN_STRENGTH_RESET_VAL 0x0
#define IAXXX_PAD_CTRL_CLK_IN_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_CLK_IN_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_CLK_IN_STRENGTH_DECL (7:6)

/*** PAD_CTRL_COMMA_0 (0x40003004) ***/
/*
 * This register is used for pad COMMA_0's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_COMMA_0_ADDR (0x40003004)
#define IAXXX_PAD_CTRL_COMMA_0_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMA_0_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMA_0_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMA_0_RESET_VAL 0x00000079

/*
 * This field is used to control Driver Disabled State Control for pad
 * COMMA_0, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_COMMA_0_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_COMMA_0_DDST_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_0_DDST_POS 0
#define IAXXX_PAD_CTRL_COMMA_0_DDST_SIZE 2
#define IAXXX_PAD_CTRL_COMMA_0_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad COMMA_0.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_COMMA_0_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_COMMA_0_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_0_REN_POS 3
#define IAXXX_PAD_CTRL_COMMA_0_REN_SIZE 1
#define IAXXX_PAD_CTRL_COMMA_0_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad COMMA_0.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_COMMA_0_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_COMMA_0_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_0_SMT_POS 4
#define IAXXX_PAD_CTRL_COMMA_0_SMT_SIZE 1
#define IAXXX_PAD_CTRL_COMMA_0_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad COMMA_0.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_COMMA_0_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_COMMA_0_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_0_SR_POS 5
#define IAXXX_PAD_CTRL_COMMA_0_SR_SIZE 1
#define IAXXX_PAD_CTRL_COMMA_0_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad COMMA_0.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_COMMA_0_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_COMMA_0_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_0_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_COMMA_0_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_COMMA_0_STRENGTH_DECL (7:6)

/*** PAD_CTRL_COMMA_1 (0x40003008) ***/
/*
 * This register is used for pad COMMA_1's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_COMMA_1_ADDR (0x40003008)
#define IAXXX_PAD_CTRL_COMMA_1_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMA_1_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMA_1_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMA_1_RESET_VAL 0x00000079

/*
 * This field is used to control Driver Disabled State Control for pad
 * COMMA_1, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_COMMA_1_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_COMMA_1_DDST_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_1_DDST_POS 0
#define IAXXX_PAD_CTRL_COMMA_1_DDST_SIZE 2
#define IAXXX_PAD_CTRL_COMMA_1_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad COMMA_1.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_COMMA_1_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_COMMA_1_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_1_REN_POS 3
#define IAXXX_PAD_CTRL_COMMA_1_REN_SIZE 1
#define IAXXX_PAD_CTRL_COMMA_1_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad COMMA_1.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_COMMA_1_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_COMMA_1_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_1_SMT_POS 4
#define IAXXX_PAD_CTRL_COMMA_1_SMT_SIZE 1
#define IAXXX_PAD_CTRL_COMMA_1_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad COMMA_1.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_COMMA_1_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_COMMA_1_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_1_SR_POS 5
#define IAXXX_PAD_CTRL_COMMA_1_SR_SIZE 1
#define IAXXX_PAD_CTRL_COMMA_1_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad COMMA_1.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_COMMA_1_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_COMMA_1_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_1_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_COMMA_1_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_COMMA_1_STRENGTH_DECL (7:6)

/*** PAD_CTRL_COMMA_2 (0x4000300c) ***/
/*
 * This register is used for pad COMMA_2's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_COMMA_2_ADDR (0x4000300c)
#define IAXXX_PAD_CTRL_COMMA_2_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMA_2_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMA_2_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMA_2_RESET_VAL 0x00000079

/*
 * This field is used to control Driver Disabled State Control for pad
 * COMMA_2, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_COMMA_2_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_COMMA_2_DDST_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_2_DDST_POS 0
#define IAXXX_PAD_CTRL_COMMA_2_DDST_SIZE 2
#define IAXXX_PAD_CTRL_COMMA_2_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad COMMA_2.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_COMMA_2_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_COMMA_2_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_2_REN_POS 3
#define IAXXX_PAD_CTRL_COMMA_2_REN_SIZE 1
#define IAXXX_PAD_CTRL_COMMA_2_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad COMMA_2.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_COMMA_2_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_COMMA_2_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_2_SMT_POS 4
#define IAXXX_PAD_CTRL_COMMA_2_SMT_SIZE 1
#define IAXXX_PAD_CTRL_COMMA_2_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad COMMA_2.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_COMMA_2_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_COMMA_2_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_2_SR_POS 5
#define IAXXX_PAD_CTRL_COMMA_2_SR_SIZE 1
#define IAXXX_PAD_CTRL_COMMA_2_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad COMMA_2.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_COMMA_2_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_COMMA_2_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_2_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_COMMA_2_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_COMMA_2_STRENGTH_DECL (7:6)

/*** PAD_CTRL_COMMA_3 (0x40003010) ***/
/*
 * This register is used for pad COMMA_3's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_COMMA_3_ADDR (0x40003010)
#define IAXXX_PAD_CTRL_COMMA_3_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMA_3_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMA_3_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMA_3_RESET_VAL 0x00000079

/*
 * This field is used to control Driver Disabled State Control for pad
 * COMMA_3, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_COMMA_3_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_COMMA_3_DDST_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_3_DDST_POS 0
#define IAXXX_PAD_CTRL_COMMA_3_DDST_SIZE 2
#define IAXXX_PAD_CTRL_COMMA_3_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad COMMA_3.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_COMMA_3_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_COMMA_3_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_3_REN_POS 3
#define IAXXX_PAD_CTRL_COMMA_3_REN_SIZE 1
#define IAXXX_PAD_CTRL_COMMA_3_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad COMMA_3.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_COMMA_3_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_COMMA_3_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_3_SMT_POS 4
#define IAXXX_PAD_CTRL_COMMA_3_SMT_SIZE 1
#define IAXXX_PAD_CTRL_COMMA_3_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad COMMA_3.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_COMMA_3_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_COMMA_3_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_3_SR_POS 5
#define IAXXX_PAD_CTRL_COMMA_3_SR_SIZE 1
#define IAXXX_PAD_CTRL_COMMA_3_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad COMMA_3.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_COMMA_3_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_COMMA_3_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMA_3_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_COMMA_3_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_COMMA_3_STRENGTH_DECL (7:6)

/*** PAD_CTRL_COMMB_0 (0x40003014) ***/
/*
 * This register is used for pad COMMB_0's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_COMMB_0_ADDR (0x40003014)
#define IAXXX_PAD_CTRL_COMMB_0_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMB_0_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMB_0_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMB_0_RESET_VAL 0x00000079

/*
 * This field is used to control Driver Disabled State Control for pad
 * COMMB_0, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_COMMB_0_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_COMMB_0_DDST_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_0_DDST_POS 0
#define IAXXX_PAD_CTRL_COMMB_0_DDST_SIZE 2
#define IAXXX_PAD_CTRL_COMMB_0_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad COMMB_0.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_COMMB_0_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_COMMB_0_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_0_REN_POS 3
#define IAXXX_PAD_CTRL_COMMB_0_REN_SIZE 1
#define IAXXX_PAD_CTRL_COMMB_0_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad COMMB_0.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_COMMB_0_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_COMMB_0_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_0_SMT_POS 4
#define IAXXX_PAD_CTRL_COMMB_0_SMT_SIZE 1
#define IAXXX_PAD_CTRL_COMMB_0_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad COMMB_0.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_COMMB_0_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_COMMB_0_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_0_SR_POS 5
#define IAXXX_PAD_CTRL_COMMB_0_SR_SIZE 1
#define IAXXX_PAD_CTRL_COMMB_0_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad COMMB_0.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_COMMB_0_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_COMMB_0_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_0_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_COMMB_0_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_COMMB_0_STRENGTH_DECL (7:6)

/*** PAD_CTRL_COMMB_1 (0x40003018) ***/
/*
 * This register is used for pad COMMB_1's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_COMMB_1_ADDR (0x40003018)
#define IAXXX_PAD_CTRL_COMMB_1_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMB_1_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMB_1_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMB_1_RESET_VAL 0x00000079

/*
 * This field is used to control Driver Disabled State Control for pad
 * COMMB_1, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_COMMB_1_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_COMMB_1_DDST_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_1_DDST_POS 0
#define IAXXX_PAD_CTRL_COMMB_1_DDST_SIZE 2
#define IAXXX_PAD_CTRL_COMMB_1_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad COMMB_1.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_COMMB_1_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_COMMB_1_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_1_REN_POS 3
#define IAXXX_PAD_CTRL_COMMB_1_REN_SIZE 1
#define IAXXX_PAD_CTRL_COMMB_1_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad COMMB_1.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_COMMB_1_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_COMMB_1_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_1_SMT_POS 4
#define IAXXX_PAD_CTRL_COMMB_1_SMT_SIZE 1
#define IAXXX_PAD_CTRL_COMMB_1_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad COMMB_1.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_COMMB_1_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_COMMB_1_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_1_SR_POS 5
#define IAXXX_PAD_CTRL_COMMB_1_SR_SIZE 1
#define IAXXX_PAD_CTRL_COMMB_1_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad COMMB_1.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_COMMB_1_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_COMMB_1_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_1_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_COMMB_1_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_COMMB_1_STRENGTH_DECL (7:6)

/*** PAD_CTRL_COMMB_2 (0x4000301c) ***/
/*
 * This register is used for pad COMMB_2's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_COMMB_2_ADDR (0x4000301c)
#define IAXXX_PAD_CTRL_COMMB_2_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMB_2_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMB_2_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMB_2_RESET_VAL 0x00000079

/*
 * This field is used to control Driver Disabled State Control for pad
 * COMMB_2, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_COMMB_2_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_COMMB_2_DDST_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_2_DDST_POS 0
#define IAXXX_PAD_CTRL_COMMB_2_DDST_SIZE 2
#define IAXXX_PAD_CTRL_COMMB_2_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad COMMB_2.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_COMMB_2_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_COMMB_2_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_2_REN_POS 3
#define IAXXX_PAD_CTRL_COMMB_2_REN_SIZE 1
#define IAXXX_PAD_CTRL_COMMB_2_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad COMMB_2.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_COMMB_2_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_COMMB_2_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_2_SMT_POS 4
#define IAXXX_PAD_CTRL_COMMB_2_SMT_SIZE 1
#define IAXXX_PAD_CTRL_COMMB_2_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad COMMB_2.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_COMMB_2_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_COMMB_2_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_2_SR_POS 5
#define IAXXX_PAD_CTRL_COMMB_2_SR_SIZE 1
#define IAXXX_PAD_CTRL_COMMB_2_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad COMMB_2.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_COMMB_2_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_COMMB_2_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_2_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_COMMB_2_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_COMMB_2_STRENGTH_DECL (7:6)

/*** PAD_CTRL_COMMB_3 (0x40003020) ***/
/*
 * This register is used for pad COMMB_3's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_COMMB_3_ADDR (0x40003020)
#define IAXXX_PAD_CTRL_COMMB_3_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMB_3_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMB_3_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_COMMB_3_RESET_VAL 0x00000079

/*
 * This field is used to control Driver Disabled State Control for pad
 * COMMB_3, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_COMMB_3_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_COMMB_3_DDST_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_3_DDST_POS 0
#define IAXXX_PAD_CTRL_COMMB_3_DDST_SIZE 2
#define IAXXX_PAD_CTRL_COMMB_3_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad COMMB_3.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_COMMB_3_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_COMMB_3_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_3_REN_POS 3
#define IAXXX_PAD_CTRL_COMMB_3_REN_SIZE 1
#define IAXXX_PAD_CTRL_COMMB_3_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad COMMB_3.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_COMMB_3_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_COMMB_3_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_3_SMT_POS 4
#define IAXXX_PAD_CTRL_COMMB_3_SMT_SIZE 1
#define IAXXX_PAD_CTRL_COMMB_3_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad COMMB_3.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_COMMB_3_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_COMMB_3_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_3_SR_POS 5
#define IAXXX_PAD_CTRL_COMMB_3_SR_SIZE 1
#define IAXXX_PAD_CTRL_COMMB_3_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad COMMB_3.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_COMMB_3_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_COMMB_3_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_COMMB_3_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_COMMB_3_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_COMMB_3_STRENGTH_DECL (7:6)

/*** PAD_CTRL_GPIO_0 (0x40003024) ***/
/*
 * This register is used for pad GPIO_0's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_GPIO_0_ADDR (0x40003024)
#define IAXXX_PAD_CTRL_GPIO_0_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_GPIO_0_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_GPIO_0_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_GPIO_0_RESET_VAL 0x0000007a

/*
 * This field is used to control Driver Disabled State Control for pad
 * GPIO_0, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_GPIO_0_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_GPIO_0_DDST_RESET_VAL 0x2
#define IAXXX_PAD_CTRL_GPIO_0_DDST_POS 0
#define IAXXX_PAD_CTRL_GPIO_0_DDST_SIZE 2
#define IAXXX_PAD_CTRL_GPIO_0_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad GPIO_0.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_GPIO_0_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_GPIO_0_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_GPIO_0_REN_POS 3
#define IAXXX_PAD_CTRL_GPIO_0_REN_SIZE 1
#define IAXXX_PAD_CTRL_GPIO_0_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad GPIO_0.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_GPIO_0_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_GPIO_0_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_GPIO_0_SMT_POS 4
#define IAXXX_PAD_CTRL_GPIO_0_SMT_SIZE 1
#define IAXXX_PAD_CTRL_GPIO_0_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad GPIO_0.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_GPIO_0_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_GPIO_0_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_GPIO_0_SR_POS 5
#define IAXXX_PAD_CTRL_GPIO_0_SR_SIZE 1
#define IAXXX_PAD_CTRL_GPIO_0_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad GPIO_0.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_GPIO_0_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_GPIO_0_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_GPIO_0_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_GPIO_0_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_GPIO_0_STRENGTH_DECL (7:6)

/*** PAD_CTRL_GPIO_1 (0x40003028) ***/
/*
 * This register is used for pad GPIO_1's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_GPIO_1_ADDR (0x40003028)
#define IAXXX_PAD_CTRL_GPIO_1_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_GPIO_1_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_GPIO_1_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_GPIO_1_RESET_VAL 0x0000007a

/*
 * This field is used to control Driver Disabled State Control for pad
 * GPIO_1, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_GPIO_1_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_GPIO_1_DDST_RESET_VAL 0x2
#define IAXXX_PAD_CTRL_GPIO_1_DDST_POS 0
#define IAXXX_PAD_CTRL_GPIO_1_DDST_SIZE 2
#define IAXXX_PAD_CTRL_GPIO_1_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad GPIO_1.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_GPIO_1_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_GPIO_1_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_GPIO_1_REN_POS 3
#define IAXXX_PAD_CTRL_GPIO_1_REN_SIZE 1
#define IAXXX_PAD_CTRL_GPIO_1_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad GPIO_1.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_GPIO_1_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_GPIO_1_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_GPIO_1_SMT_POS 4
#define IAXXX_PAD_CTRL_GPIO_1_SMT_SIZE 1
#define IAXXX_PAD_CTRL_GPIO_1_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad GPIO_1.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_GPIO_1_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_GPIO_1_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_GPIO_1_SR_POS 5
#define IAXXX_PAD_CTRL_GPIO_1_SR_SIZE 1
#define IAXXX_PAD_CTRL_GPIO_1_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad GPIO_1.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_GPIO_1_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_GPIO_1_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_GPIO_1_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_GPIO_1_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_GPIO_1_STRENGTH_DECL (7:6)

/*** PAD_CTRL_IRQ (0x4000302c) ***/
/*
 * This register is used for pad IRQ's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_IRQ_ADDR (0x4000302c)
#define IAXXX_PAD_CTRL_IRQ_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_IRQ_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_IRQ_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_IRQ_RESET_VAL 0x0000007a

/*
 * This field is used to control Driver Disabled State Control for pad IRQ,
 * to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus keeper)
 * functions for the pad. Note that MUX_SEL selects the source of the output
 * enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_IRQ_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_IRQ_DDST_RESET_VAL 0x2
#define IAXXX_PAD_CTRL_IRQ_DDST_POS 0
#define IAXXX_PAD_CTRL_IRQ_DDST_SIZE 2
#define IAXXX_PAD_CTRL_IRQ_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad IRQ.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_IRQ_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_IRQ_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_IRQ_REN_POS 3
#define IAXXX_PAD_CTRL_IRQ_REN_SIZE 1
#define IAXXX_PAD_CTRL_IRQ_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad IRQ.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_IRQ_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_IRQ_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_IRQ_SMT_POS 4
#define IAXXX_PAD_CTRL_IRQ_SMT_SIZE 1
#define IAXXX_PAD_CTRL_IRQ_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad IRQ.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_IRQ_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_IRQ_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_IRQ_SR_POS 5
#define IAXXX_PAD_CTRL_IRQ_SR_SIZE 1
#define IAXXX_PAD_CTRL_IRQ_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad IRQ.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_IRQ_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_IRQ_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_IRQ_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_IRQ_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_IRQ_STRENGTH_DECL (7:6)

/*** PAD_CTRL_JTAG_DBG_TCK (0x40003030) ***/
/*
 * This register is used for pad JTAG_DBG_TCK's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_JTAG_DBG_TCK_ADDR (0x40003030)
#define IAXXX_PAD_CTRL_JTAG_DBG_TCK_MASK_VAL 0x00000013
#define IAXXX_PAD_CTRL_JTAG_DBG_TCK_RMASK_VAL 0x00000013
#define IAXXX_PAD_CTRL_JTAG_DBG_TCK_WMASK_VAL 0x00000013
#define IAXXX_PAD_CTRL_JTAG_DBG_TCK_RESET_VAL 0x00000011

/*
 * This field is used to control Driver Disabled State Control for pad
 * JTAG_DBG_TCK, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_JTAG_DBG_TCK_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_JTAG_DBG_TCK_DDST_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_JTAG_DBG_TCK_DDST_POS 0
#define IAXXX_PAD_CTRL_JTAG_DBG_TCK_DDST_SIZE 2
#define IAXXX_PAD_CTRL_JTAG_DBG_TCK_DDST_DECL (1:0)

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad JTAG_DBG_TCK.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_JTAG_DBG_TCK_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_JTAG_DBG_TCK_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_JTAG_DBG_TCK_SMT_POS 4
#define IAXXX_PAD_CTRL_JTAG_DBG_TCK_SMT_SIZE 1
#define IAXXX_PAD_CTRL_JTAG_DBG_TCK_SMT_DECL 4

/*** PAD_CTRL_JTAG_DBG_TDI (0x40003034) ***/
/*
 * This register is used for pad JTAG_DBG_TDI's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_JTAG_DBG_TDI_ADDR (0x40003034)
#define IAXXX_PAD_CTRL_JTAG_DBG_TDI_MASK_VAL 0x00000013
#define IAXXX_PAD_CTRL_JTAG_DBG_TDI_RMASK_VAL 0x00000013
#define IAXXX_PAD_CTRL_JTAG_DBG_TDI_WMASK_VAL 0x00000013
#define IAXXX_PAD_CTRL_JTAG_DBG_TDI_RESET_VAL 0x00000011

/*
 * This field is used to control Driver Disabled State Control for pad
 * JTAG_DBG_TDI, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_JTAG_DBG_TDI_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_JTAG_DBG_TDI_DDST_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_JTAG_DBG_TDI_DDST_POS 0
#define IAXXX_PAD_CTRL_JTAG_DBG_TDI_DDST_SIZE 2
#define IAXXX_PAD_CTRL_JTAG_DBG_TDI_DDST_DECL (1:0)

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad JTAG_DBG_TDI.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_JTAG_DBG_TDI_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_JTAG_DBG_TDI_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_JTAG_DBG_TDI_SMT_POS 4
#define IAXXX_PAD_CTRL_JTAG_DBG_TDI_SMT_SIZE 1
#define IAXXX_PAD_CTRL_JTAG_DBG_TDI_SMT_DECL 4

/*** PAD_CTRL_JTAG_DBG_TDO (0x40003038) ***/
/*
 * This register is used for pad JTAG_DBG_TDO's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_ADDR (0x40003038)
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_MASK_VAL 0x000000e3
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_RMASK_VAL 0x000000e3
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_WMASK_VAL 0x000000e3
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_RESET_VAL 0x00000060

/*
 * This field is used to control Driver Disabled State Control for pad
 * JTAG_DBG_TDO, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_DDST_RESET_VAL 0x0
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_DDST_POS 0
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_DDST_SIZE 2
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_DDST_DECL (1:0)

/*
 * This field is used to control Slew Rate control for pad JTAG_DBG_TDO.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_SR_POS 5
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_SR_SIZE 1
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad
 * JTAG_DBG_TDO.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_JTAG_DBG_TDO_STRENGTH_DECL (7:6)

/*** PAD_CTRL_JTAG_DBG_TMS (0x4000303c) ***/
/*
 * This register is used for pad JTAG_DBG_TMS's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_ADDR (0x4000303c)
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_MASK_VAL 0x000000f3
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_RMASK_VAL 0x000000f3
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_WMASK_VAL 0x000000f3
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_RESET_VAL 0x00000031

/*
 * This field is used to control Driver Disabled State Control for pad
 * JTAG_DBG_TMS, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_DDST_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_DDST_POS 0
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_DDST_SIZE 2
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_DDST_DECL (1:0)

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad JTAG_DBG_TMS.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_SMT_POS 4
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_SMT_SIZE 1
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad JTAG_DBG_TMS.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_SR_POS 5
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_SR_SIZE 1
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad
 * JTAG_DBG_TMS.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_STRENGTH_RESET_VAL 0x0
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_JTAG_DBG_TMS_STRENGTH_DECL (7:6)

/*** PAD_CTRL_PORTA_CLK (0x40003040) ***/
/*
 * This register is used for pad PORTA_CLK's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_PORTA_CLK_ADDR (0x40003040)
#define IAXXX_PAD_CTRL_PORTA_CLK_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTA_CLK_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTA_CLK_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTA_CLK_RESET_VAL 0x0000007a

/*
 * This field is used to control Driver Disabled State Control for pad
 * PORTA_CLK, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_PORTA_CLK_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_PORTA_CLK_DDST_RESET_VAL 0x2
#define IAXXX_PAD_CTRL_PORTA_CLK_DDST_POS 0
#define IAXXX_PAD_CTRL_PORTA_CLK_DDST_SIZE 2
#define IAXXX_PAD_CTRL_PORTA_CLK_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad
 * PORTA_CLK.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_PORTA_CLK_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_PORTA_CLK_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTA_CLK_REN_POS 3
#define IAXXX_PAD_CTRL_PORTA_CLK_REN_SIZE 1
#define IAXXX_PAD_CTRL_PORTA_CLK_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad PORTA_CLK.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_PORTA_CLK_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_PORTA_CLK_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTA_CLK_SMT_POS 4
#define IAXXX_PAD_CTRL_PORTA_CLK_SMT_SIZE 1
#define IAXXX_PAD_CTRL_PORTA_CLK_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad PORTA_CLK.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_PORTA_CLK_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_PORTA_CLK_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTA_CLK_SR_POS 5
#define IAXXX_PAD_CTRL_PORTA_CLK_SR_SIZE 1
#define IAXXX_PAD_CTRL_PORTA_CLK_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad PORTA_CLK.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_PORTA_CLK_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_PORTA_CLK_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTA_CLK_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_PORTA_CLK_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_PORTA_CLK_STRENGTH_DECL (7:6)

/*** PAD_CTRL_PORTA_DI (0x40003044) ***/
/*
 * This register is used for pad PORTA_DI's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_PORTA_DI_ADDR (0x40003044)
#define IAXXX_PAD_CTRL_PORTA_DI_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTA_DI_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTA_DI_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTA_DI_RESET_VAL 0x0000007a

/*
 * This field is used to control Driver Disabled State Control for pad
 * PORTA_DI, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_PORTA_DI_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_PORTA_DI_DDST_RESET_VAL 0x2
#define IAXXX_PAD_CTRL_PORTA_DI_DDST_POS 0
#define IAXXX_PAD_CTRL_PORTA_DI_DDST_SIZE 2
#define IAXXX_PAD_CTRL_PORTA_DI_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad
 * PORTA_DI.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_PORTA_DI_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_PORTA_DI_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTA_DI_REN_POS 3
#define IAXXX_PAD_CTRL_PORTA_DI_REN_SIZE 1
#define IAXXX_PAD_CTRL_PORTA_DI_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad PORTA_DI.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_PORTA_DI_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_PORTA_DI_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTA_DI_SMT_POS 4
#define IAXXX_PAD_CTRL_PORTA_DI_SMT_SIZE 1
#define IAXXX_PAD_CTRL_PORTA_DI_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad PORTA_DI.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_PORTA_DI_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_PORTA_DI_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTA_DI_SR_POS 5
#define IAXXX_PAD_CTRL_PORTA_DI_SR_SIZE 1
#define IAXXX_PAD_CTRL_PORTA_DI_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad PORTA_DI.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_PORTA_DI_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_PORTA_DI_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTA_DI_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_PORTA_DI_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_PORTA_DI_STRENGTH_DECL (7:6)

/*** PAD_CTRL_PORTA_DO (0x40003048) ***/
/*
 * This register is used for pad PORTA_DO's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_PORTA_DO_ADDR (0x40003048)
#define IAXXX_PAD_CTRL_PORTA_DO_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTA_DO_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTA_DO_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTA_DO_RESET_VAL 0x0000007a

/*
 * This field is used to control Driver Disabled State Control for pad
 * PORTA_DO, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_PORTA_DO_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_PORTA_DO_DDST_RESET_VAL 0x2
#define IAXXX_PAD_CTRL_PORTA_DO_DDST_POS 0
#define IAXXX_PAD_CTRL_PORTA_DO_DDST_SIZE 2
#define IAXXX_PAD_CTRL_PORTA_DO_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad
 * PORTA_DO.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_PORTA_DO_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_PORTA_DO_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTA_DO_REN_POS 3
#define IAXXX_PAD_CTRL_PORTA_DO_REN_SIZE 1
#define IAXXX_PAD_CTRL_PORTA_DO_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad PORTA_DO.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_PORTA_DO_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_PORTA_DO_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTA_DO_SMT_POS 4
#define IAXXX_PAD_CTRL_PORTA_DO_SMT_SIZE 1
#define IAXXX_PAD_CTRL_PORTA_DO_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad PORTA_DO.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_PORTA_DO_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_PORTA_DO_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTA_DO_SR_POS 5
#define IAXXX_PAD_CTRL_PORTA_DO_SR_SIZE 1
#define IAXXX_PAD_CTRL_PORTA_DO_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad PORTA_DO.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_PORTA_DO_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_PORTA_DO_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTA_DO_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_PORTA_DO_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_PORTA_DO_STRENGTH_DECL (7:6)

/*** PAD_CTRL_PORTA_FS (0x4000304c) ***/
/*
 * This register is used for pad PORTA_FS's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_PORTA_FS_ADDR (0x4000304c)
#define IAXXX_PAD_CTRL_PORTA_FS_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTA_FS_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTA_FS_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTA_FS_RESET_VAL 0x0000007a

/*
 * This field is used to control Driver Disabled State Control for pad
 * PORTA_FS, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_PORTA_FS_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_PORTA_FS_DDST_RESET_VAL 0x2
#define IAXXX_PAD_CTRL_PORTA_FS_DDST_POS 0
#define IAXXX_PAD_CTRL_PORTA_FS_DDST_SIZE 2
#define IAXXX_PAD_CTRL_PORTA_FS_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad
 * PORTA_FS.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_PORTA_FS_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_PORTA_FS_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTA_FS_REN_POS 3
#define IAXXX_PAD_CTRL_PORTA_FS_REN_SIZE 1
#define IAXXX_PAD_CTRL_PORTA_FS_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad PORTA_FS.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_PORTA_FS_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_PORTA_FS_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTA_FS_SMT_POS 4
#define IAXXX_PAD_CTRL_PORTA_FS_SMT_SIZE 1
#define IAXXX_PAD_CTRL_PORTA_FS_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad PORTA_FS.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_PORTA_FS_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_PORTA_FS_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTA_FS_SR_POS 5
#define IAXXX_PAD_CTRL_PORTA_FS_SR_SIZE 1
#define IAXXX_PAD_CTRL_PORTA_FS_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad PORTA_FS.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_PORTA_FS_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_PORTA_FS_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTA_FS_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_PORTA_FS_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_PORTA_FS_STRENGTH_DECL (7:6)

/*** PAD_CTRL_PORTB_CLK (0x40003050) ***/
/*
 * This register is used for pad PORTB_CLK's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_PORTB_CLK_ADDR (0x40003050)
#define IAXXX_PAD_CTRL_PORTB_CLK_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTB_CLK_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTB_CLK_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTB_CLK_RESET_VAL 0x0000007a

/*
 * This field is used to control Driver Disabled State Control for pad
 * PORTB_CLK, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_PORTB_CLK_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_PORTB_CLK_DDST_RESET_VAL 0x2
#define IAXXX_PAD_CTRL_PORTB_CLK_DDST_POS 0
#define IAXXX_PAD_CTRL_PORTB_CLK_DDST_SIZE 2
#define IAXXX_PAD_CTRL_PORTB_CLK_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad
 * PORTB_CLK.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_PORTB_CLK_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_PORTB_CLK_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTB_CLK_REN_POS 3
#define IAXXX_PAD_CTRL_PORTB_CLK_REN_SIZE 1
#define IAXXX_PAD_CTRL_PORTB_CLK_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad PORTB_CLK.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_PORTB_CLK_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_PORTB_CLK_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTB_CLK_SMT_POS 4
#define IAXXX_PAD_CTRL_PORTB_CLK_SMT_SIZE 1
#define IAXXX_PAD_CTRL_PORTB_CLK_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad PORTB_CLK.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_PORTB_CLK_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_PORTB_CLK_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTB_CLK_SR_POS 5
#define IAXXX_PAD_CTRL_PORTB_CLK_SR_SIZE 1
#define IAXXX_PAD_CTRL_PORTB_CLK_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad PORTB_CLK.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_PORTB_CLK_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_PORTB_CLK_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTB_CLK_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_PORTB_CLK_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_PORTB_CLK_STRENGTH_DECL (7:6)

/*** PAD_CTRL_PORTB_DI (0x40003054) ***/
/*
 * This register is used for pad PORTB_DI's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_PORTB_DI_ADDR (0x40003054)
#define IAXXX_PAD_CTRL_PORTB_DI_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTB_DI_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTB_DI_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTB_DI_RESET_VAL 0x0000007a

/*
 * This field is used to control Driver Disabled State Control for pad
 * PORTB_DI, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_PORTB_DI_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_PORTB_DI_DDST_RESET_VAL 0x2
#define IAXXX_PAD_CTRL_PORTB_DI_DDST_POS 0
#define IAXXX_PAD_CTRL_PORTB_DI_DDST_SIZE 2
#define IAXXX_PAD_CTRL_PORTB_DI_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad
 * PORTB_DI.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_PORTB_DI_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_PORTB_DI_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTB_DI_REN_POS 3
#define IAXXX_PAD_CTRL_PORTB_DI_REN_SIZE 1
#define IAXXX_PAD_CTRL_PORTB_DI_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad PORTB_DI.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_PORTB_DI_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_PORTB_DI_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTB_DI_SMT_POS 4
#define IAXXX_PAD_CTRL_PORTB_DI_SMT_SIZE 1
#define IAXXX_PAD_CTRL_PORTB_DI_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad PORTB_DI.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_PORTB_DI_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_PORTB_DI_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTB_DI_SR_POS 5
#define IAXXX_PAD_CTRL_PORTB_DI_SR_SIZE 1
#define IAXXX_PAD_CTRL_PORTB_DI_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad PORTB_DI.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_PORTB_DI_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_PORTB_DI_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTB_DI_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_PORTB_DI_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_PORTB_DI_STRENGTH_DECL (7:6)

/*** PAD_CTRL_PORTB_DO (0x40003058) ***/
/*
 * This register is used for pad PORTB_DO's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_PORTB_DO_ADDR (0x40003058)
#define IAXXX_PAD_CTRL_PORTB_DO_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTB_DO_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTB_DO_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTB_DO_RESET_VAL 0x0000007a

/*
 * This field is used to control Driver Disabled State Control for pad
 * PORTB_DO, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_PORTB_DO_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_PORTB_DO_DDST_RESET_VAL 0x2
#define IAXXX_PAD_CTRL_PORTB_DO_DDST_POS 0
#define IAXXX_PAD_CTRL_PORTB_DO_DDST_SIZE 2
#define IAXXX_PAD_CTRL_PORTB_DO_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad
 * PORTB_DO.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_PORTB_DO_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_PORTB_DO_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTB_DO_REN_POS 3
#define IAXXX_PAD_CTRL_PORTB_DO_REN_SIZE 1
#define IAXXX_PAD_CTRL_PORTB_DO_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad PORTB_DO.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_PORTB_DO_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_PORTB_DO_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTB_DO_SMT_POS 4
#define IAXXX_PAD_CTRL_PORTB_DO_SMT_SIZE 1
#define IAXXX_PAD_CTRL_PORTB_DO_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad PORTB_DO.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_PORTB_DO_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_PORTB_DO_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTB_DO_SR_POS 5
#define IAXXX_PAD_CTRL_PORTB_DO_SR_SIZE 1
#define IAXXX_PAD_CTRL_PORTB_DO_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad PORTB_DO.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_PORTB_DO_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_PORTB_DO_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTB_DO_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_PORTB_DO_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_PORTB_DO_STRENGTH_DECL (7:6)

/*** PAD_CTRL_PORTB_FS (0x4000305c) ***/
/*
 * This register is used for pad PORTB_FS's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_PORTB_FS_ADDR (0x4000305c)
#define IAXXX_PAD_CTRL_PORTB_FS_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTB_FS_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTB_FS_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTB_FS_RESET_VAL 0x0000007a

/*
 * This field is used to control Driver Disabled State Control for pad
 * PORTB_FS, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_PORTB_FS_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_PORTB_FS_DDST_RESET_VAL 0x2
#define IAXXX_PAD_CTRL_PORTB_FS_DDST_POS 0
#define IAXXX_PAD_CTRL_PORTB_FS_DDST_SIZE 2
#define IAXXX_PAD_CTRL_PORTB_FS_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad
 * PORTB_FS.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_PORTB_FS_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_PORTB_FS_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTB_FS_REN_POS 3
#define IAXXX_PAD_CTRL_PORTB_FS_REN_SIZE 1
#define IAXXX_PAD_CTRL_PORTB_FS_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad PORTB_FS.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_PORTB_FS_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_PORTB_FS_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTB_FS_SMT_POS 4
#define IAXXX_PAD_CTRL_PORTB_FS_SMT_SIZE 1
#define IAXXX_PAD_CTRL_PORTB_FS_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad PORTB_FS.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_PORTB_FS_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_PORTB_FS_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTB_FS_SR_POS 5
#define IAXXX_PAD_CTRL_PORTB_FS_SR_SIZE 1
#define IAXXX_PAD_CTRL_PORTB_FS_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad PORTB_FS.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_PORTB_FS_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_PORTB_FS_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTB_FS_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_PORTB_FS_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_PORTB_FS_STRENGTH_DECL (7:6)

/*** PAD_CTRL_PORTC_CLK (0x40003060) ***/
/*
 * This register is used for pad PORTC_CLK's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_PORTC_CLK_ADDR (0x40003060)
#define IAXXX_PAD_CTRL_PORTC_CLK_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTC_CLK_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTC_CLK_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTC_CLK_RESET_VAL 0x0000007a

/*
 * This field is used to control Driver Disabled State Control for pad
 * PORTC_CLK, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_PORTC_CLK_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_PORTC_CLK_DDST_RESET_VAL 0x2
#define IAXXX_PAD_CTRL_PORTC_CLK_DDST_POS 0
#define IAXXX_PAD_CTRL_PORTC_CLK_DDST_SIZE 2
#define IAXXX_PAD_CTRL_PORTC_CLK_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad
 * PORTC_CLK.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_PORTC_CLK_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_PORTC_CLK_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTC_CLK_REN_POS 3
#define IAXXX_PAD_CTRL_PORTC_CLK_REN_SIZE 1
#define IAXXX_PAD_CTRL_PORTC_CLK_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad PORTC_CLK.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_PORTC_CLK_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_PORTC_CLK_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTC_CLK_SMT_POS 4
#define IAXXX_PAD_CTRL_PORTC_CLK_SMT_SIZE 1
#define IAXXX_PAD_CTRL_PORTC_CLK_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad PORTC_CLK.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_PORTC_CLK_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_PORTC_CLK_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTC_CLK_SR_POS 5
#define IAXXX_PAD_CTRL_PORTC_CLK_SR_SIZE 1
#define IAXXX_PAD_CTRL_PORTC_CLK_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad PORTC_CLK.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_PORTC_CLK_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_PORTC_CLK_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTC_CLK_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_PORTC_CLK_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_PORTC_CLK_STRENGTH_DECL (7:6)

/*** PAD_CTRL_PORTC_DI (0x40003064) ***/
/*
 * This register is used for pad PORTC_DI's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_PORTC_DI_ADDR (0x40003064)
#define IAXXX_PAD_CTRL_PORTC_DI_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTC_DI_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTC_DI_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTC_DI_RESET_VAL 0x0000007a

/*
 * This field is used to control Driver Disabled State Control for pad
 * PORTC_DI, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_PORTC_DI_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_PORTC_DI_DDST_RESET_VAL 0x2
#define IAXXX_PAD_CTRL_PORTC_DI_DDST_POS 0
#define IAXXX_PAD_CTRL_PORTC_DI_DDST_SIZE 2
#define IAXXX_PAD_CTRL_PORTC_DI_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad
 * PORTC_DI.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_PORTC_DI_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_PORTC_DI_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTC_DI_REN_POS 3
#define IAXXX_PAD_CTRL_PORTC_DI_REN_SIZE 1
#define IAXXX_PAD_CTRL_PORTC_DI_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad PORTC_DI.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_PORTC_DI_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_PORTC_DI_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTC_DI_SMT_POS 4
#define IAXXX_PAD_CTRL_PORTC_DI_SMT_SIZE 1
#define IAXXX_PAD_CTRL_PORTC_DI_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad PORTC_DI.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_PORTC_DI_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_PORTC_DI_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTC_DI_SR_POS 5
#define IAXXX_PAD_CTRL_PORTC_DI_SR_SIZE 1
#define IAXXX_PAD_CTRL_PORTC_DI_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad PORTC_DI.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_PORTC_DI_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_PORTC_DI_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTC_DI_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_PORTC_DI_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_PORTC_DI_STRENGTH_DECL (7:6)

/*** PAD_CTRL_PORTC_DO (0x40003068) ***/
/*
 * This register is used for pad PORTC_DO's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_PORTC_DO_ADDR (0x40003068)
#define IAXXX_PAD_CTRL_PORTC_DO_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTC_DO_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTC_DO_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTC_DO_RESET_VAL 0x0000007a

/*
 * This field is used to control Driver Disabled State Control for pad
 * PORTC_DO, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_PORTC_DO_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_PORTC_DO_DDST_RESET_VAL 0x2
#define IAXXX_PAD_CTRL_PORTC_DO_DDST_POS 0
#define IAXXX_PAD_CTRL_PORTC_DO_DDST_SIZE 2
#define IAXXX_PAD_CTRL_PORTC_DO_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad
 * PORTC_DO.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_PORTC_DO_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_PORTC_DO_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTC_DO_REN_POS 3
#define IAXXX_PAD_CTRL_PORTC_DO_REN_SIZE 1
#define IAXXX_PAD_CTRL_PORTC_DO_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad PORTC_DO.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_PORTC_DO_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_PORTC_DO_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTC_DO_SMT_POS 4
#define IAXXX_PAD_CTRL_PORTC_DO_SMT_SIZE 1
#define IAXXX_PAD_CTRL_PORTC_DO_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad PORTC_DO.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_PORTC_DO_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_PORTC_DO_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTC_DO_SR_POS 5
#define IAXXX_PAD_CTRL_PORTC_DO_SR_SIZE 1
#define IAXXX_PAD_CTRL_PORTC_DO_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad PORTC_DO.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_PORTC_DO_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_PORTC_DO_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTC_DO_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_PORTC_DO_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_PORTC_DO_STRENGTH_DECL (7:6)

/*** PAD_CTRL_PORTC_FS (0x4000306c) ***/
/*
 * This register is used for pad PORTC_FS's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_PORTC_FS_ADDR (0x4000306c)
#define IAXXX_PAD_CTRL_PORTC_FS_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTC_FS_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTC_FS_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_PORTC_FS_RESET_VAL 0x0000007a

/*
 * This field is used to control Driver Disabled State Control for pad
 * PORTC_FS, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_PORTC_FS_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_PORTC_FS_DDST_RESET_VAL 0x2
#define IAXXX_PAD_CTRL_PORTC_FS_DDST_POS 0
#define IAXXX_PAD_CTRL_PORTC_FS_DDST_SIZE 2
#define IAXXX_PAD_CTRL_PORTC_FS_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad
 * PORTC_FS.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_PORTC_FS_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_PORTC_FS_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTC_FS_REN_POS 3
#define IAXXX_PAD_CTRL_PORTC_FS_REN_SIZE 1
#define IAXXX_PAD_CTRL_PORTC_FS_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad PORTC_FS.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_PORTC_FS_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_PORTC_FS_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTC_FS_SMT_POS 4
#define IAXXX_PAD_CTRL_PORTC_FS_SMT_SIZE 1
#define IAXXX_PAD_CTRL_PORTC_FS_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad PORTC_FS.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_PORTC_FS_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_PORTC_FS_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTC_FS_SR_POS 5
#define IAXXX_PAD_CTRL_PORTC_FS_SR_SIZE 1
#define IAXXX_PAD_CTRL_PORTC_FS_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad PORTC_FS.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_PORTC_FS_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_PORTC_FS_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PORTC_FS_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_PORTC_FS_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_PORTC_FS_STRENGTH_DECL (7:6)

/*** PAD_CTRL_PWR_GOOD (0x40003070) ***/
/*
 * This register is used for pad PWR_GOOD's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_PWR_GOOD_ADDR (0x40003070)
#define IAXXX_PAD_CTRL_PWR_GOOD_MASK_VAL 0x000000e3
#define IAXXX_PAD_CTRL_PWR_GOOD_RMASK_VAL 0x000000e3
#define IAXXX_PAD_CTRL_PWR_GOOD_WMASK_VAL 0x000000e3
#define IAXXX_PAD_CTRL_PWR_GOOD_RESET_VAL 0x00000060

/*
 * This field is used to control Driver Disabled State Control for pad
 * PWR_GOOD, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_PWR_GOOD_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_PWR_GOOD_DDST_RESET_VAL 0x0
#define IAXXX_PAD_CTRL_PWR_GOOD_DDST_POS 0
#define IAXXX_PAD_CTRL_PWR_GOOD_DDST_SIZE 2
#define IAXXX_PAD_CTRL_PWR_GOOD_DDST_DECL (1:0)

/*
 * This field is used to control Slew Rate control for pad PWR_GOOD.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_PWR_GOOD_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_PWR_GOOD_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PWR_GOOD_SR_POS 5
#define IAXXX_PAD_CTRL_PWR_GOOD_SR_SIZE 1
#define IAXXX_PAD_CTRL_PWR_GOOD_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad PWR_GOOD.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_PWR_GOOD_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_PWR_GOOD_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_PWR_GOOD_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_PWR_GOOD_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_PWR_GOOD_STRENGTH_DECL (7:6)

/*** PAD_CTRL_PWR_RESET_N (0x40003074) ***/
/*
 * This register is used for pad PWR_RESET_N's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_PWR_RESET_N_ADDR (0x40003074)
#define IAXXX_PAD_CTRL_PWR_RESET_N_MASK_VAL 0x00000000
#define IAXXX_PAD_CTRL_PWR_RESET_N_RMASK_VAL 0x00000000
#define IAXXX_PAD_CTRL_PWR_RESET_N_WMASK_VAL 0x00000000
#define IAXXX_PAD_CTRL_PWR_RESET_N_RESET_VAL 0x00000000

/*** PAD_CTRL_SYS_RESET_N (0x40003078) ***/
/*
 * This register is used for pad SYS_RESET_N's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_SYS_RESET_N_ADDR (0x40003078)
#define IAXXX_PAD_CTRL_SYS_RESET_N_MASK_VAL 0x00000000
#define IAXXX_PAD_CTRL_SYS_RESET_N_RMASK_VAL 0x00000000
#define IAXXX_PAD_CTRL_SYS_RESET_N_WMASK_VAL 0x00000000
#define IAXXX_PAD_CTRL_SYS_RESET_N_RESET_VAL 0x00000000

/*** PAD_CTRL_TEST (0x4000307c) ***/
/*
 * This register is used for pad TEST's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_TEST_ADDR (0x4000307c)
#define IAXXX_PAD_CTRL_TEST_MASK_VAL 0x00000010
#define IAXXX_PAD_CTRL_TEST_RMASK_VAL 0x00000010
#define IAXXX_PAD_CTRL_TEST_WMASK_VAL 0x00000010
#define IAXXX_PAD_CTRL_TEST_RESET_VAL 0x00000010

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad TEST.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_TEST_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_TEST_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_TEST_SMT_POS 4
#define IAXXX_PAD_CTRL_TEST_SMT_SIZE 1
#define IAXXX_PAD_CTRL_TEST_SMT_DECL 4

/*** PAD_CTRL_TRACE_CLK (0x40003080) ***/
/*
 * This register is used for pad TRACE_CLK's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_TRACE_CLK_ADDR (0x40003080)
#define IAXXX_PAD_CTRL_TRACE_CLK_MASK_VAL 0x000000e3
#define IAXXX_PAD_CTRL_TRACE_CLK_RMASK_VAL 0x000000e3
#define IAXXX_PAD_CTRL_TRACE_CLK_WMASK_VAL 0x000000e3
#define IAXXX_PAD_CTRL_TRACE_CLK_RESET_VAL 0x00000060

/*
 * This field is used to control Driver Disabled State Control for pad
 * TRACE_CLK, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_TRACE_CLK_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_TRACE_CLK_DDST_RESET_VAL 0x0
#define IAXXX_PAD_CTRL_TRACE_CLK_DDST_POS 0
#define IAXXX_PAD_CTRL_TRACE_CLK_DDST_SIZE 2
#define IAXXX_PAD_CTRL_TRACE_CLK_DDST_DECL (1:0)

/*
 * This field is used to control Slew Rate control for pad TRACE_CLK.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_TRACE_CLK_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_TRACE_CLK_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_TRACE_CLK_SR_POS 5
#define IAXXX_PAD_CTRL_TRACE_CLK_SR_SIZE 1
#define IAXXX_PAD_CTRL_TRACE_CLK_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad TRACE_CLK.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_TRACE_CLK_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_TRACE_CLK_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_TRACE_CLK_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_TRACE_CLK_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_TRACE_CLK_STRENGTH_DECL (7:6)

/*** PAD_CTRL_TRACE_DATA (0x40003084) ***/
/*
 * This register is used for pad TRACE_DATA's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_TRACE_DATA_ADDR (0x40003084)
#define IAXXX_PAD_CTRL_TRACE_DATA_MASK_VAL 0x000000e3
#define IAXXX_PAD_CTRL_TRACE_DATA_RMASK_VAL 0x000000e3
#define IAXXX_PAD_CTRL_TRACE_DATA_WMASK_VAL 0x000000e3
#define IAXXX_PAD_CTRL_TRACE_DATA_RESET_VAL 0x00000060

/*
 * This field is used to control Driver Disabled State Control for pad
 * TRACE_DATA, to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus
 * keeper) functions for the pad. Note that MUX_SEL selects the source of the
 * output enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_TRACE_DATA_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_TRACE_DATA_DDST_RESET_VAL 0x0
#define IAXXX_PAD_CTRL_TRACE_DATA_DDST_POS 0
#define IAXXX_PAD_CTRL_TRACE_DATA_DDST_SIZE 2
#define IAXXX_PAD_CTRL_TRACE_DATA_DDST_DECL (1:0)

/*
 * This field is used to control Slew Rate control for pad TRACE_DATA.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_TRACE_DATA_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_TRACE_DATA_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_TRACE_DATA_SR_POS 5
#define IAXXX_PAD_CTRL_TRACE_DATA_SR_SIZE 1
#define IAXXX_PAD_CTRL_TRACE_DATA_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad TRACE_DATA.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_TRACE_DATA_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_TRACE_DATA_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_TRACE_DATA_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_TRACE_DATA_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_TRACE_DATA_STRENGTH_DECL (7:6)

/*** PAD_CTRL_WAKE (0x40003088) ***/
/*
 * This register is used for pad WAKE's electrical control.
 * INTERNAL: Refer to the <a href="#io_pad_control_diagram">IO Function and
 * PAD Control diagram</a> to understand these controls better.
 */
#define IAXXX_PAD_CTRL_WAKE_ADDR (0x40003088)
#define IAXXX_PAD_CTRL_WAKE_MASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_WAKE_RMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_WAKE_WMASK_VAL 0x000000fb
#define IAXXX_PAD_CTRL_WAKE_RESET_VAL 0x0000007a

/*
 * This field is used to control Driver Disabled State Control for pad WAKE,
 * to select between Hi-Z, Pull-up, Pull-down, or Repeater (bus keeper)
 * functions for the pad. Note that MUX_SEL selects the source of the output
 * enable (OEN) for the pad.
 * If OEN = 0, the output is driven, then DDST has no effect.
 * Else, OEN = 1, and DDST function is selected as follows.
 *   0x0: Hi-Z (Normal operation)
 *   0x1: weak 1 (Pull-up)
 *   0x2: weak 0 (Pull-down)
 *   0x3: Repeater (Bus keeper)
 */
#define IAXXX_PAD_CTRL_WAKE_DDST_MASK 0x00000003
#define IAXXX_PAD_CTRL_WAKE_DDST_RESET_VAL 0x2
#define IAXXX_PAD_CTRL_WAKE_DDST_POS 0
#define IAXXX_PAD_CTRL_WAKE_DDST_SIZE 2
#define IAXXX_PAD_CTRL_WAKE_DDST_DECL (1:0)

/*
 * This field is used to control active high Receiver Enable for pad WAKE.
 *   0x0: Receiver disabled, input to core logic driven to "0".
 *   0x1: Receiver enabled.
 */
#define IAXXX_PAD_CTRL_WAKE_REN_MASK 0x00000008
#define IAXXX_PAD_CTRL_WAKE_REN_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_WAKE_REN_POS 3
#define IAXXX_PAD_CTRL_WAKE_REN_SIZE 1
#define IAXXX_PAD_CTRL_WAKE_REN_DECL 3

/*
 * This field is used to control active high Schmitt trigger (Hysteresis)
 * select for pad WAKE.
 *   0x0: No hysteresis
 *   0x1: Schmitt trigger enabled
 */
#define IAXXX_PAD_CTRL_WAKE_SMT_MASK 0x00000010
#define IAXXX_PAD_CTRL_WAKE_SMT_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_WAKE_SMT_POS 4
#define IAXXX_PAD_CTRL_WAKE_SMT_SIZE 1
#define IAXXX_PAD_CTRL_WAKE_SMT_DECL 4

/*
 * This field is used to control Slew Rate control for pad WAKE.
 *   0x0: Slow (half frequency)
 *   0x1: Fast
 */
#define IAXXX_PAD_CTRL_WAKE_SR_MASK 0x00000020
#define IAXXX_PAD_CTRL_WAKE_SR_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_WAKE_SR_POS 5
#define IAXXX_PAD_CTRL_WAKE_SR_SIZE 1
#define IAXXX_PAD_CTRL_WAKE_SR_DECL 5

/*
 * This field is used to control Drive Strength selection for pad WAKE.
 *   0x0: 2mA
 *   0x1: 4mA
 *   0x2: 8mA
 *   0x3: 12mA
 */
#define IAXXX_PAD_CTRL_WAKE_STRENGTH_MASK 0x000000c0
#define IAXXX_PAD_CTRL_WAKE_STRENGTH_RESET_VAL 0x1
#define IAXXX_PAD_CTRL_WAKE_STRENGTH_POS 6
#define IAXXX_PAD_CTRL_WAKE_STRENGTH_SIZE 2
#define IAXXX_PAD_CTRL_WAKE_STRENGTH_DECL (7:6)

/* Number of registers in the module */
#define IAXXX_PAD_CTRL_REG_NUM 35

#endif /* __IAXXX_REGISTER_DEFS_PAD_CTRL_H__*/
