/*
 * iaxxx-register-defs-ioctrl-pos.h
 *
 * Copyright (c) 2018 Knowles, inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/**********************************************************
 * This file is generated by running a format script
 * on header files shared by Firmware.
 *
 * DO NOT EDIT.
 *
 *********************************************************/

#ifndef __IAXXX_REGISTER_DEFS_IO_CTRL_POS_H__
#define __IAXXX_REGISTER_DEFS_IO_CTRL_POS_H__

#define IAXXX_IO_CTRL_MUX_SEL_POS 0

#define IAXXX_IO_CTRL_MUX_SEL_SYS_VAL 0x0
#define IAXXX_IO_CTRL_MUX_SEL_LDO_VAL 0x0
#define IAXXX_IO_CTRL_MUX_SEL_SW_LOR_VAL 0x1
#define IAXXX_IO_CTRL_MUX_SEL_JTAG_VAL 0x2
#define IAXXX_IO_CTRL_MUX_SEL_TRACE_VAL 0x2
#define IAXXX_IO_CTRL_MUX_SEL_SWJDP_VAL 0x3
#define IAXXX_IO_CTRL_MUX_SEL_REFCLK_VAL 0x4
#define IAXXX_IO_CTRL_MUX_SEL_MCLK_VAL 0x4
#define IAXXX_IO_CTRL_MUX_SEL_I2S_VAL 0x5
#define IAXXX_IO_CTRL_MUX_SEL_DMIC_VAL 0x6
#define IAXXX_IO_CTRL_MUX_SEL_PDM_CLK_VAL 0x7
#define IAXXX_IO_CTRL_MUX_SEL_DMIC_PT_VAL 0x8
#define IAXXX_IO_CTRL_MUX_SEL_ADC_VAL 0x9
#define IAXXX_IO_CTRL_MUX_SEL_CDC_CLK_VAL 0xa
#define IAXXX_IO_CTRL_MUX_SEL_EXT_SYNC_VAL 0xb
#define IAXXX_IO_CTRL_MUX_SEL_PCM_VAL 0xc
#define IAXXX_IO_CTRL_MUX_SEL_PCM_PT_VAL 0xd
#define IAXXX_IO_CTRL_MUX_SEL_I2C_VAL 0xe
#define IAXXX_IO_CTRL_MUX_SEL_UART_VAL 0xf
#define IAXXX_IO_CTRL_MUX_SEL_UART_HS_VAL 0x10
#define IAXXX_IO_CTRL_MUX_SEL_SPI_VAL 0x11
#define IAXXX_IO_CTRL_MUX_SEL_SPI0_VAL 0x12
#define IAXXX_IO_CTRL_MUX_SEL_SPI1_VAL 0x13
#define IAXXX_IO_CTRL_MUX_SEL_AFG_VAL 0x14
#define IAXXX_IO_CTRL_MUX_SEL_GPIO_VAL 0x15
#define IAXXX_IO_CTRL_MUX_SEL_FI_VAL 0x16
#define IAXXX_IO_CTRL_MUX_SEL_DMX_FO_VAL 0x16
#define IAXXX_IO_CTRL_MUX_SEL_IO2STMR_VAL 0x17
#define IAXXX_IO_CTRL_MUX_SEL_HMD_FO_VAL 0x17
#define IAXXX_IO_CTRL_MUX_SEL_RESET_VAL  0x1F

#define IAXXX_IO_CTRL_AND_SEL_SYS_POS 5
#define IAXXX_IO_CTRL_AND_SEL_LDO_POS 5
#define IAXXX_IO_CTRL_AND_SEL_SW_LOR_POS 6
#define IAXXX_IO_CTRL_AND_SEL_JTAG_POS 7
#define IAXXX_IO_CTRL_AND_SEL_TRACE_POS 7
#define IAXXX_IO_CTRL_AND_SEL_SWJDP_POS 8
#define IAXXX_IO_CTRL_AND_SEL_REFCLK_POS 9
#define IAXXX_IO_CTRL_AND_SEL_MCLK_POS 9
#define IAXXX_IO_CTRL_AND_SEL_I2S_POS 10
#define IAXXX_IO_CTRL_AND_SEL_DMIC_POS 11
#define IAXXX_IO_CTRL_AND_SEL_PDM_CLK_POS 12
#define IAXXX_IO_CTRL_AND_SEL_DMIC_PT_POS 13
#define IAXXX_IO_CTRL_AND_SEL_ADC_POS 14
#define IAXXX_IO_CTRL_AND_SEL_CDC_CLK_POS 15
#define IAXXX_IO_CTRL_AND_SEL_EXT_SYNC_POS 16
#define IAXXX_IO_CTRL_AND_SEL_PCM_POS 17
#define IAXXX_IO_CTRL_AND_SEL_PCM_PT_POS 18
#define IAXXX_IO_CTRL_AND_SEL_I2C_POS 19
#define IAXXX_IO_CTRL_AND_SEL_UART_POS 20
#define IAXXX_IO_CTRL_AND_SEL_UART_HS_POS 21
#define IAXXX_IO_CTRL_AND_SEL_SPI_POS 22
#define IAXXX_IO_CTRL_AND_SEL_SPI0_POS 23
#define IAXXX_IO_CTRL_AND_SEL_SPI1_POS 24
#define IAXXX_IO_CTRL_AND_SEL_AFG_POS 25
#define IAXXX_IO_CTRL_AND_SEL_GPIO_POS 26
#define IAXXX_IO_CTRL_AND_SEL_FI_POS 27
#define IAXXX_IO_CTRL_AND_SEL_DMX_FO_POS 27
#define IAXXX_IO_CTRL_AND_SEL_IO2STMR_POS 28
#define IAXXX_IO_CTRL_AND_SEL_HMD_FO_POS 28

#endif /* __IAXXX_REGISTER_DEFS_IO_CTRL_POS_H__ */
