/*
 * iaxxx-register-defs-msw.h
 *
 * Copyright (c) 2018 Knowles, inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/**********************************************************
 * This file is generated by running a format script
 * on header files shared by Firmware.
 *
 * DO NOT EDIT.
 *
 *********************************************************/

#ifndef __IAXXX_REGISTER_DEFS_MSW_H__
#define __IAXXX_REGISTER_DEFS_MSW_H__

/*** The base address for this set of registers ***/
#define IAXXX_MSW_REGS_ADDR (0x40038000)

/*** MSW_MEM_ALLOC_POOL_TN_RAM_0 (0x40038000) ***/
/*
 * This register is used to allocate POOL_TN_RAM_0 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_0_ADDR (0x40038000)
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_0_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_0_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_0_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_0_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_0_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_0_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_0_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_0_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_0_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_TN_RAM_1 (0x40038004) ***/
/*
 * This register is used to allocate POOL_TN_RAM_1 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_1_ADDR (0x40038004)
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_1_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_1_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_1_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_1_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_1_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_1_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_1_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_1_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_1_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_TN_RAM_2 (0x40038008) ***/
/*
 * This register is used to allocate POOL_TN_RAM_2 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_2_ADDR (0x40038008)
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_2_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_2_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_2_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_2_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_2_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_2_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_2_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_2_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_2_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_TN_RAM_3 (0x4003800c) ***/
/*
 * This register is used to allocate POOL_TN_RAM_3 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_3_ADDR (0x4003800c)
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_3_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_3_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_3_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_3_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_3_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_3_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_3_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_3_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_3_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_SM_RAM_0 (0x40038010) ***/
/*
 * This register is used to allocate POOL_SM_RAM_0 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_0_ADDR (0x40038010)
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_0_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_0_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_0_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_0_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_0_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_0_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_0_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_0_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_0_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_SM_RAM_1 (0x40038014) ***/
/*
 * This register is used to allocate POOL_SM_RAM_1 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_1_ADDR (0x40038014)
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_1_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_1_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_1_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_1_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_1_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_1_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_1_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_1_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_1_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_SM_RAM_2 (0x40038018) ***/
/*
 * This register is used to allocate POOL_SM_RAM_2 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_2_ADDR (0x40038018)
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_2_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_2_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_2_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_2_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_2_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_2_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_2_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_2_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_2_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_SM_RAM_3 (0x4003801c) ***/
/*
 * This register is used to allocate POOL_SM_RAM_3 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_3_ADDR (0x4003801c)
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_3_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_3_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_3_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_3_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_3_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_3_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_3_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_3_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_3_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_LG_RAM_0 (0x40038020) ***/
/*
 * This register is used to allocate POOL_LG_RAM_0 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_0_ADDR (0x40038020)
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_0_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_0_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_0_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_0_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_0_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_0_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_0_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_0_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_0_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_LG_RAM_1 (0x40038024) ***/
/*
 * This register is used to allocate POOL_LG_RAM_1 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_1_ADDR (0x40038024)
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_1_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_1_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_1_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_1_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_1_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_1_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_1_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_1_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_1_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_LG_RAM_2 (0x40038028) ***/
/*
 * This register is used to allocate POOL_LG_RAM_2 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_2_ADDR (0x40038028)
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_2_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_2_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_2_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_2_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_2_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_2_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_2_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_2_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_2_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_LG_RAM_3 (0x4003802c) ***/
/*
 * This register is used to allocate POOL_LG_RAM_3 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_3_ADDR (0x4003802c)
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_3_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_3_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_3_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_3_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_3_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_3_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_3_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_3_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_3_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_HG_RAM_00 (0x40038030) ***/
/*
 * This register is used to allocate POOL_HG_RAM_00 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_00_ADDR (0x40038030)
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_00_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_00_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_00_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_00_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_00_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_00_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_00_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_00_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_00_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_HG_RAM_01 (0x40038034) ***/
/*
 * This register is used to allocate POOL_HG_RAM_01 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_01_ADDR (0x40038034)
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_01_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_01_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_01_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_01_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_01_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_01_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_01_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_01_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_01_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_HG_RAM_02 (0x40038038) ***/
/*
 * This register is used to allocate POOL_HG_RAM_02 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_02_ADDR (0x40038038)
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_02_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_02_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_02_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_02_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_02_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_02_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_02_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_02_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_02_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_HG_RAM_03 (0x4003803c) ***/
/*
 * This register is used to allocate POOL_HG_RAM_03 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_03_ADDR (0x4003803c)
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_03_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_03_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_03_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_03_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_03_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_03_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_03_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_03_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_03_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_HG_RAM_04 (0x40038040) ***/
/*
 * This register is used to allocate POOL_HG_RAM_04 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_04_ADDR (0x40038040)
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_04_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_04_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_04_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_04_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_04_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_04_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_04_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_04_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_04_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_HG_RAM_05 (0x40038044) ***/
/*
 * This register is used to allocate POOL_HG_RAM_05 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_05_ADDR (0x40038044)
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_05_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_05_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_05_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_05_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_05_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_05_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_05_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_05_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_05_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_HG_RAM_06 (0x40038048) ***/
/*
 * This register is used to allocate POOL_HG_RAM_06 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_06_ADDR (0x40038048)
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_06_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_06_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_06_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_06_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_06_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_06_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_06_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_06_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_06_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_HG_RAM_07 (0x4003804c) ***/
/*
 * This register is used to allocate POOL_HG_RAM_07 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_07_ADDR (0x4003804c)
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_07_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_07_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_07_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_07_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_07_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_07_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_07_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_07_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_07_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_HG_RAM_08 (0x40038050) ***/
/*
 * This register is used to allocate POOL_HG_RAM_08 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_08_ADDR (0x40038050)
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_08_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_08_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_08_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_08_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_08_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_08_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_08_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_08_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_08_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_HG_RAM_09 (0x40038054) ***/
/*
 * This register is used to allocate POOL_HG_RAM_09 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_09_ADDR (0x40038054)
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_09_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_09_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_09_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_09_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_09_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_09_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_09_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_09_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_09_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_HG_RAM_10 (0x40038058) ***/
/*
 * This register is used to allocate POOL_HG_RAM_10 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_10_ADDR (0x40038058)
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_10_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_10_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_10_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_10_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_10_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_10_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_10_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_10_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_10_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_HG_RAM_11 (0x4003805c) ***/
/*
 * This register is used to allocate POOL_HG_RAM_11 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_11_ADDR (0x4003805c)
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_11_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_11_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_11_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_11_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_11_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_11_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_11_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_11_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_11_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_HG_RAM_12 (0x40038060) ***/
/*
 * This register is used to allocate POOL_HG_RAM_12 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_12_ADDR (0x40038060)
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_12_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_12_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_12_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_12_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_12_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_12_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_12_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_12_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_12_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_HG_RAM_13 (0x40038064) ***/
/*
 * This register is used to allocate POOL_HG_RAM_13 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_13_ADDR (0x40038064)
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_13_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_13_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_13_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_13_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_13_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_13_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_13_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_13_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_13_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_HG_RAM_14 (0x40038068) ***/
/*
 * This register is used to allocate POOL_HG_RAM_14 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_14_ADDR (0x40038068)
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_14_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_14_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_14_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_14_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_14_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_14_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_14_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_14_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_14_CPU_INTERFACE_DECL (2:0)

/*** MSW_MEM_ALLOC_POOL_HG_RAM_15 (0x4003806c) ***/
/*
 * This register is used to allocate POOL_HG_RAM_15 memory to a CPU, through
 * an interface.
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_15_ADDR (0x4003806c)
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_15_MASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_15_RMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_15_WMASK_VAL 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_15_RESET_VAL 0x00000004

/*
 * This is the mapping for allocating this tile to a processor through an
 * interface.
 *
 Field encoding values:
 *   0x0: DMX_IRAM
 *   0x1: DMX_DRAM0
 *   0x2: HMD_IRAM
 *   0x3: HMD_DRAM0
 *   0x4: NONE
 *   0x5: NONE
 *   0x6: NONE
 *   0x7: NONE
 */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_15_CPU_INTERFACE_MASK 0x00000007
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_15_CPU_INTERFACE_RESET_VAL 0x4
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_15_CPU_INTERFACE_POS 0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_15_CPU_INTERFACE_SIZE 3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_15_CPU_INTERFACE_DECL (2:0)

/* Field encodings for register MEM_ALLOC_POOL_TN_RAM_0's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_0_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_0_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_0_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_0_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_0_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_TN_RAM_1's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_1_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_1_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_1_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_1_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_1_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_TN_RAM_2's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_2_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_2_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_2_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_2_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_2_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_TN_RAM_3's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_3_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_3_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_3_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_3_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_TN_RAM_3_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_SM_RAM_0's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_0_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_0_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_0_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_0_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_0_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_SM_RAM_1's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_1_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_1_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_1_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_1_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_1_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_SM_RAM_2's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_2_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_2_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_2_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_2_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_2_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_SM_RAM_3's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_3_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_3_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_3_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_3_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_SM_RAM_3_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_LG_RAM_0's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_0_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_0_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_0_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_0_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_0_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_LG_RAM_1's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_1_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_1_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_1_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_1_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_1_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_LG_RAM_2's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_2_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_2_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_2_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_2_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_2_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_LG_RAM_3's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_3_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_3_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_3_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_3_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_LG_RAM_3_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_HG_RAM_00's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_00_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_00_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_00_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_00_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_00_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_HG_RAM_01's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_01_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_01_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_01_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_01_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_01_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_HG_RAM_02's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_02_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_02_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_02_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_02_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_02_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_HG_RAM_03's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_03_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_03_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_03_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_03_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_03_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_HG_RAM_04's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_04_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_04_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_04_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_04_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_04_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_HG_RAM_05's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_05_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_05_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_05_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_05_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_05_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_HG_RAM_06's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_06_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_06_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_06_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_06_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_06_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_HG_RAM_07's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_07_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_07_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_07_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_07_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_07_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_HG_RAM_08's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_08_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_08_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_08_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_08_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_08_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_HG_RAM_09's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_09_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_09_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_09_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_09_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_09_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_HG_RAM_10's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_10_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_10_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_10_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_10_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_10_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_HG_RAM_11's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_11_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_11_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_11_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_11_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_11_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_HG_RAM_12's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_12_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_12_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_12_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_12_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_12_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_HG_RAM_13's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_13_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_13_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_13_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_13_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_13_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_HG_RAM_14's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_14_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_14_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_14_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_14_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_14_CPU_INTERFACE_NONE_VAL 0x4

/* Field encodings for register MEM_ALLOC_POOL_HG_RAM_15's field CPU_INTERFACE. */
/* This is the mapping for allocating this tile to a processor through an */
/* interface. */

/* Field encoding values: */
/*   0x0: DMX_IRAM */
/*   0x1: DMX_DRAM0 */
/*   0x2: HMD_IRAM */
/*   0x3: HMD_DRAM0 */
/*   0x4: NONE */
/*   0x5: NONE */
/*   0x6: NONE */
/*   0x7: NONE */
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_15_CPU_INTERFACE_DMX_IRAM_VAL 0x0
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_15_CPU_INTERFACE_DMX_DRAM0_VAL 0x1
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_15_CPU_INTERFACE_HMD_IRAM_VAL 0x2
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_15_CPU_INTERFACE_HMD_DRAM0_VAL 0x3
#define IAXXX_MSW_MEM_ALLOC_POOL_HG_RAM_15_CPU_INTERFACE_NONE_VAL 0x4

/* Number of registers in the module */
#define IAXXX_MSW_REG_NUM 28

#endif /* __IAXXX_REGISTER_DEFS_MSW_H__*/
