/*
 * iaxxx-register-defs-pad-ctrl-field.h
 *
 * Copyright (c) 2018 Knowles, inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/**********************************************************
 * This file is generated by running a format script
 * on header files shared by Firmware.
 *
 * DO NOT EDIT.
 *
 *********************************************************/

#ifndef REGISTER_DEFS_PAD_CTRL_FIELD_H
#define IAXXX_REGISTER_DEFS_PAD_CTRL_FIELD_H

#define IAXXX_PAD_HI_Z            (0)
#define IAXXX_PAD_PULL_UP         (1)
#define IAXXX_PAD_PULL_DOWN       (2)
#define IAXXX_PAD_BUS_KEEPER      (3)

#endif /* REGISTER_DEFS_PAD_CTRL_FIELD_H */
