#
# Makefile for MTK Bandwidth device drivers.
#

# general options
EXTRA_CFLAGS      +=  -Idrivers/mstar2/include/sys/common
EXTRA_CFLAGS      +=  -Idrivers/mstar2/include
EXTRA_CFLAGS      +=  -Idrivers/mstar2/drv/miu
# specific options
EXTRA_CFLAGS      +=

# files
obj-$(CONFIG_MTK_MIU_BW)             := mtk_bw.o
#mtk-bw-objs    := mtk_bw.o

