#
# Makefile for MStar CPU IO device drivers.
#

# general options
EXTRA_CFLAGS      +=  -Idrivers/mstar2/include
EXTRA_CFLAGS      +=  -Idrivers/mstar2/drv/cpu/arm64/generic/cpu_io

# specific options
EXTRA_CFLAGS      +=

# files
obj-y             += mdrv_cpu_io.o
