/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/******************************************************************************
 *
 * This file is provided under a dual license.  When you use or
 * distribute this software, you may choose to be licensed under
 * version 2 of the GNU General Public License ("GPLv2 License")
 * or BSD License.
 *
 * GPLv2 License
 *
 * Copyright(C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * BSD LICENSE
 *
 * Copyright(C) 2019 MediaTek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

/* Copyright (C) 2014 Cadence Design Systems.  All rights reserved           */
/* THIS FILE IS AUTOMATICALLY GENERATED BY CADENCE BLUEPRINT, DO NOT EDIT    */
/*                                                                           */


#ifndef __REG_PCIE_UDMA_ADDRMAP_H__
#define __REG_PCIE_UDMA_ADDRMAP_H__

#include "pcie_udma_addrmap_macro.h"

struct pcie_udma_addrmap__udma_one_ch_regs {
  volatile uint32_t channel_ctrl;                 /*        0x0 - 0x4        */
  volatile uint32_t channel_sp_l;                 /*        0x4 - 0x8        */
  volatile uint32_t channel_sp_u;                 /*        0x8 - 0xc        */
  volatile uint32_t channel_attr_l;               /*        0xc - 0x10       */
  volatile uint32_t channel_attr_u;               /*       0x10 - 0x14       */
};

struct pcie_udma_addrmap__udma_common_regs {
  volatile uint32_t common_udma_int;              /*        0x0 - 0x4        */
  volatile uint32_t common_udma_int_ena;          /*        0x4 - 0x8        */
  volatile uint32_t common_udma_int_dis;          /*        0x8 - 0xc        */
  volatile uint32_t common_udma_ib_ecc_uncorrectable_errors;
                                                  /*        0xc - 0x10       */
  volatile uint32_t common_udma_ib_ecc_correctable_errors;
                                                  /*       0x10 - 0x14       */
  volatile uint32_t common_udma_ob_ecc_uncorrectable_errors;
                                                  /*       0x14 - 0x18       */
  volatile uint32_t common_udma_ob_ecc_correctable_errors;
                                                  /*       0x18 - 0x1c       */
  volatile char pad__0[0x3c];                     /*       0x1c - 0x58       */
  volatile uint32_t common_udma_cap_ver;          /*       0x58 - 0x5c       */
  volatile uint32_t common_udma_config;           /*       0x5c - 0x60       */
};

struct pcie_udma_addrmap {
  struct pcie_udma_addrmap__udma_one_ch_regs dma_ch0;
                                                  /*        0x0 - 0x14       */
  struct pcie_udma_addrmap__udma_one_ch_regs dma_ch1;
                                                  /*       0x14 - 0x28       */
  volatile char pad__0[0x78];                     /*       0x28 - 0xa0       */
  struct pcie_udma_addrmap__udma_common_regs dma_common;
                                                  /*       0xa0 - 0x100      */
};

#endif /* __REG_PCIE_UDMA_ADDRMAP_H__ */
