#
# Makefile for MStar device drivers.
#

obj-$(CONFIG_MSTAR_TUNER)                                        += tuner/

obj-$(CONFIG_MSTAR_DISH)                                         += dish/

obj-$(CONFIG_MSTAR_TUNER)                                        += BypassEWBSIIC/

